### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by zjtt** [paradox37/monorepo#1]
How did you solve this problem? thank.   [Uncaught SyntaxError: Unexpected token ?](https://github.com/vitejs/vite/issues/14175)
![image](https://github.com/paradox37/monorepo/assets/22001904/dd8d3b92-8111-4ce2-84cf-14e79b4497dc)

**Comment by paradox37** [comment]
Everything is [written in that issue](https://github.com/vitejs/vite/issues/14175#issuecomment-1693629270).
